--
- name: Configure Juniper MPLS Switch
  hosts: 2300c
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  #tasks:
    #- include_vars: "./access-var.yml"

    #- name: Build JunOS agnostic config template
    #  template: src=template/agnostic_config.set.j2 dest={{build_dir}}/agnostic_config.set
    #  with_items: agnostic_config

    #- name: Build JunOS EX switch configuration
    #  template: src=template/sw_config.set.j2 dest={{build_dir}}/sw_config.set
    #  with_items: junos_ex_config

    #- name: Build Access switch configuration
    #  template: src=template/access/access_config.set.j2 dest={{build_dir}}/access_config.set
    #  with_items: access_config
      
    #- name: Build Access management VRF switch configuration
    #  template: src=template/access/access_mgmt_config.set.j2 dest={{build_dir}}/access_mgmt_config.set
    #  with_items: access_mgmt_config
      
    #- name: Build Access switch AP configuration for Secure and Guest, requires management VRF
    #  template: src=template/access/access_ap_config.set.j2 dest={{build_dir}}/access_ap_config.set
    #  with_items: access_ap_config
      
    #- name: Build Access switch VoIP configuration, adds QoS, LLDP, and switch options
    #  template: src=template/access/access_voice_config.set.j2 dest={{build_dir}}/access_voice_config.set
    #  with_items: access_voice_config
      
    #- name: Build Access switch printer vlan configuration
    #  template: src=template/access/access_printer_config.set.j2 dest={{build_dir}}/access_printer_config.set
    #  with_items: access_printer_config
      
      # If you require access switch configuration for an Airtame network uncomment the next two stanzas
    #- name: Build Airtame Configuration for access switch configuration
    #  template: src=template/access/access_airtame_config.set.j2 dest={{build_dir}}/access_airtame_config.set
    #  with_items: access_airtame_config
    
    #- name: Build phpIPAM address reservation
    #  template: src=template/phpipam_config.j2 dest={{build_dir}}/phpipam_config.text
    #  with_items: phpipam_config
