---
- name: Configure Juniper MPLS Switch
  hosts: 2300c
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  tasks:
    - include_vars: "./var.yml"

    - name: Build JunOS agnostic config template
      template: src=template/junos_agnostic_config.set.j2 dest={{build_dir}}/junos_agnostic_config.set
      with_items: junos_agnostic_config

    - name: Build JunOS EX switch configuration
      template: src=template/junos_ex_config.set.j2 dest={{build_dir}}/junos_ex_config.set
      with_items: junos_ex_config


    #- name: Build MPLS switch configuration
     # block: src=template/junos_mpls-sw_config.set.j2 dest={{build_dir}}/junos_agnostic_config.set
     # with_items: junos_mplssw_config

    # If you require a L2 Segment for a SIP VRF uncomment the next two stanzas.
    - name: Build MPLS SIP L2 confiugration
      template: src=template/junos_mpls-sip_config.set.j2 dest={{build_dir}}/junos_mpls_sip_config.set

    - name: Build phpIPAM address reservation
      template: src=template/phpipam_config.j2 dest={{build_dir}}/phpipam_config.text
      with_items: phpipam_config
