---
- name: Configure Juniper Public Switch
  hosts: 2300c
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  tasks:
    - include_vars: "./pub-var.yml"

    - name: Build JunOS agnostic config template
      template: src=template/sw_agnostic_config.set.j2 dest={{build_dir}}/sw_agnostic_config.set
      with_items: sw_agnostic_config

    - name: Build JunOS EX switch configuration
      template: src=template/sw_config.set.j2 dest={{build_dir}}/sw_config.set
      with_items: sw_config


    - name: Build PUB switch configuration
      block: src=template/pub_sw_config.set.j2 dest={{build_dir}}/pub_sw_config.set
      with_items: pub_sw_config

    - name: Build phpIPAM address reservation
      template: src=template/phpipam_config.j2 dest={{build_dir}}/phpipam_config.text
      with_items: phpipam_config
